runtime: python39
default_expiration: 0
automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  CONFIG: gs://$PROJECT_ID-pdsa/config.json
  GIT_COMMIT:
#  PYTHONPATH: .

entrypoint: gunicorn -b :$PORT server.server:app
