runtime: python39
default_expiration: 0
automatic_scaling:
  min_instances: 0
  max_instances: 1
instance_class: F2
#F1 (default): 256MB / 600MHz - 28 free hours per day
#F2: 512MB / 1.2GHz - 14 free hours per day
#F4: 1024MB / 2.4GHz - 7 free hours per day

env_variables:
  CONFIG: gs://$PROJECT_ID-pdsa/config.json
#  LOG_LEVEL: DEBUG
#  PYTHONPATH: .

entrypoint: gunicorn -b :$PORT server.server:app --timeout 0
